### ISSUE TITLE
MNIST website down

### ISSUE THREAD

**Issue by tttamaki** [machine-perception-robotics-group/MPRGDeepLearningLectureNotebook#1]
Yan LeCunnのMNISTページがここ数日ダウンしているので，MNISTを使ったコードが動作しません．
他のソースもバックアップとして使うようなコードにならないでしょうか？

**Comment by thirakawa** [comment]
ご指摘ありがとうございます．
本件が発生したのちに，LeCanのHPからのダウンロードではなく，DropboxリンクからのMNISTをダウンロードするよう，修正を行なっておりました．
現在はオリジナルのURLが復活しているかと思いますので，本issueをcloseとさせていただきます．
よろしくお願い致します．
