### ISSUE TITLE
[typo] InputではなくImputとなっている部分がある

### ISSUE THREAD

**Issue by ensan-hcl** [machine-perception-robotics-group/MPRGDeepLearningLectureNotebook#6]
11_cnn_pytorch/08_segnet.ipynbにおいてinputではなくimputとなっているtypoがあります。

**Comment by thirakawa** [comment]
ご指摘いただき誠にありがとうございます．
imput --> inputに修正致しましたので，本issueをcloseさせていただきます．
よろしくお願い致します．
